# Generated by Django 5.0.2 on 2024-02-20 23:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
